<div id="terms_condition" class="bg-white" data-kt-drawer="true" data-kt-drawer-activate="true" data-kt-drawer-toggle="#terms_condition_button" data-kt-drawer-close="#terms_condition_close" data-kt-drawer-width="500px">
    <div class="card w-100 overflow-hidden position-relative card-rounded rounded-0">
        <div class="ribbon ribbon-triangle ribbon-top-start border-primary">
            <div class="ribbon-icon mt-n5 ms-n6">
                <img src="{{asset('img/icon.png')}}" class="w-100">
            </div>
        </div>
        <div class="card-header pe-5">
            <div class="card-title">
                <div class="d-flex justify-content-center flex-column me-3">
                    <a href="javascript:;" class="fs-4 fw-bolder text-gray-900 text-hover-primary me-1 lh-1">Terms & Conditions</a>
                    <a href="javascript:;" class="fs-7 fw-bolder me-1 lh-1">Updated at 21 May 2021</a>
                </div>
            </div>
            <div class="card-toolbar">
                <div class="btn btn-sm btn-icon btn-active-light-primary" id="terms_condition_close">
                    <span class="svg-icon svg-icon-2">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="6" y="17.3137" width="16" height="2" rx="1" transform="rotate(-45 6 17.3137)" fill="black"></rect>
                            <rect x="7.41422" y="6" width="16" height="2" rx="1" transform="rotate(45 7.41422 6)" fill="black"></rect>
                        </svg>
                    </span>
                </div>
            </div>
        </div>
        <div class="card-body hover-scroll-overlay-y">
            <h1>General Terms</h1>
            <p>By accessing and placing an order with {{config('app.name')}}, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type of communication between you and {{config('app.name')}}.</p>
            <p>Under no circumstances shall {{config('app.name')}} team be liable for any direct, indirect, special, incidental or consequential damages, including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if {{config('app.name')}} team or an authorized representative has been advised of the possibility of such damages. If your use of materials from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.</p>
            <p>{{config('app.name')}} will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve the rights to change prices and revise the resources usage policy in any moment.</p>
            
            <h1>License</h1>
            <p>{{config('app.name')}} grants you a revocable, non-exclusive, non- transferable, limited license to download, install and use the website & app strictly in accordance with the terms of this Agreement. These Terms & Conditions are a contract between you and {{config('app.name')}} ("we," "our," or "us") grants you a revocable, non-exclusive, non- transferable, limited license to download, install and use the website & app strictly in accordance with the terms of this Agreement.</p>
            <h1>Definitions and key terms</h1>
            <p>
                For this Terms & Conditions:
                <ul>
                    <li>Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                    <li>Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to CV {{config('app.name')}}, Komplek Permata Buah Batu Blok C No. 15B that is responsible for your information under this Privacy Policy.</li>
                    <li>Country: where {{config('app.name')}} or the owners/founders of {{config('app.name')}} are based, in this case is Indonesia</li>
                    <li>Customer: refers to the company, organization or person that signs up to use the {{config('app.name')}} Service to manage the relationships with your consumers or service users.</li>
                    <li>Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit {{config('app.name')}} and use the services.</li>
                    <li>IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                    <li>Personnel: refers to those individuals who are employed by {{config('app.name')}} or are under contract to perform a service on behalf of one of the parties.</li>
                    <li>Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                    <li>Service: refers to the service provided by {{config('app.name')}} as described in the relative terms (if available) and on this platform.</li>
                    <li>Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                    <li>Website: {{config('app.name')}}’s site, which can be accessed via this URL: <a href="https://yadaekidanta.com" target="_blank">https://yadaekidanta.com</a></li>
                    <li>You: a person or entity that is registered with {{config('app.name')}} to use the Services.</li>
                </ul>
            </p>
            <h1>Restrictions</h1>
            <p>
                You agree not to, and you will not permit others to:
                <ul>
                    <li>License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or make the platform available to any third party.</li>
                    <li>Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service.</li>
                    <li>Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners, suppliers or the licensors of the service.</li>
                </ul>
            </p>
            <h1>Your Suggestions</h1>
            <p>Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to us with respect to the service shall remain the sole and exclusive property of us. We shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without any credit or any compensation to you.</p>
            <h1>Your Consent</h1>
            <p>We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our service, registering an account, or making a purchase, you hereby consent to our Terms & Conditions.</p>
            <h1>Links to Other Websites</h1>
            <p>Our service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Terms & Conditions of every site You visit. We have no control over and assume no responsibility for the content, Terms & Conditions or practices of any third party sites or services.</p>
            <h1>Cookies</h1>
            <p>We use "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies.</p>
            <h1>Changes To Our Terms & Conditions</h1>
            <p>You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Service) to you or to users generally at our sole discretion, without prior notice to you. You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service. You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details or any files or other materials which is contained in your account. If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modification date below.</p>
            <h1>Modifications to Our service</h1>
            <p>We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service or any service to which it connects, with or without notice and without liability to you.</p>
            <h1>Updates to Our service</h1>
            <p>We may from time to time provide enhancements or improvements to the features/ functionality of the service, which may include patches, bug fixes, updates, upgrades and other modifications ("Updates") Updates may modify or delete certain features and/or functionalities of the service. You agree that we have no obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the service to you. You further agree that all Updates will be (i) deemed to constitute an integral part of the service, and (ii) subject to the terms and conditions of this Agreement.</p>
            <h1>Third-Party Services</h1>
            <p>We may display, include or make available third-party content (including data, information, applications and other products services) or provide links to third-party websites or services ("Third- Party Services"). You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services. Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.</p>
            <h1>Term and Termination</h1>
            <p>This Agreement shall remain in effect until terminated by you or us. We may, in its sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice. This Agreement will terminate immediately, without prior notice from us, in the event that you fail to comply with any provision of this Agreement. You may also terminate this Agreement by deleting the service and all copies thereof from your computer. Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your computer. Termination of this Agreement will not limit any of our rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement.</p>
            <h1>Copyright Infringement Notice</h1>
            <p>If you are a copyright owner or such owner’s agent and believe any material from us constitutes an infringement on your copyright, please contact us setting forth the following information: (a) a physical or electronic signature of the copyright owner or a person authorized to act on his behalf; (b) identification of the material that is claimed to be infringing; (c) your contact information, including your address, telephone number, and an email; (d) a statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and (e) the a statement that the information in the notification is accurate, and, under penalty of perjury you are authorized to act on behalf of the owner.</p>
            <h1>Indemnification</h1>
            <p>You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees, agents, partners and licensors (if any) harmless from any claim or demand, including reasonable attorneys' fees, due to or arising out of your: (a) use of the service; (b) violation of this Agreement or any law or regulation; or (c) violation of any right of a third party.</p>
            <h1>No Warranties</h1>
            <p>The service is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. To the maximum extent permitted under applicable law, we, on our own behalf and on behalf of our affiliates and our respective licensors and service providers, expressly disclaims all warranties, whether express, implied, statutory or otherwise, with respect to the service, including all implied warranties of merchantability, fitness for a particular purpose, title and non- infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice. Without limitation to the foregoing, we provide no warranty or undertaking, and makes no representation of any kind that the service will meet your requirements, achieve any intended results, be compatible or work with any other software, websites, systems or services, operate without interruption, meet any performance or reliability standards or be error free or that any errors or defects can or will be corrected.</p>
            <p>Without limiting the foregoing, neither us nor any provider makes any representation or warranty of any kind, express or implied: (i) as to the operation or availability of the service, or the information, content, and materials or products included thereon; (ii) that the service will be uninterrupted or error-free; (iii) as to the accuracy, reliability, or currency of any information or content provided through the service; or (iv) that the service, its servers, the content, or e-mails sent from or on behalf of us are free of viruses, scripts, trojan horses, worms, malware, timebombs or other harmful components. Some jurisdictions do not allow the exclusion of or limitations on implied warranties or the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you.</p>
            <h1>Limitation of Liability</h1>
            <p></p>
            <h1>Severability</h1>
            <p></p>
            <h1>Waiver</h1>
            <p></p>
            <h1>Amendments to this Agreement</h1>
            <p></p>
            <h1>Entire Agreement</h1>
            <p></p>
            <h1>Updates to Our Terms</h1>
            <p></p>
            <h1>Intellectual Property</h1>
            <p></p>
            <h1>Agreement to Arbitrate</h1>
            <p></p>
            <h1>Notice of Dispute</h1>
            <p></p>
            <h1>Binding Arbitration</h1>
            <p></p>
            <h1>Submissions and Privacy</h1>
            <p></p>
            <h1>Promotions</h1>
            <p></p>
            <h1>Typographical Errors</h1>
            <p></p>
            <h1>Miscellaneous</h1>
            <p></p>
            <h1>Disclaimer</h1>
            <p></p>
            <h1>Contact Us</h1>
            <p>
                Don't hesitate to contact us if you have any questions.
                <ul>
                    <li>Via Email: <a href="mailto:hello@yadaekidanta.com">hello@yadaekidanta.com</a></li>
                    <li>Via Phone Number: <a href="https://wa.me/6287748005611" target="_blank">0877-4800-5611</a></li>
                    <li>Via this Link: <a href="https://yadaekidanta.com/contact" target="_blank">yadaekidanta.com</a></li>
                    <li>Via this Address: Komplek Permata Buah Batu Blok C No. 15B</li>
                </ul>
            </p>
        </div>
    </div>
</div>